OETS_asn1_helper.o: OETS_asn1_helper.c
eventer.o: eventer.c ../eventer/eventer.h ../mtev_defines.h \
  ../mtev_config.h ../noitedit/strlcpy.h ../../src/utils/mtev_log.h \
  ../utils/mtev_hash.h ../../src/utils/mtev_atomic.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h ../../src/utils/mtev_sem.h
eventer_POSIX_fd_opset.o: eventer_POSIX_fd_opset.c ../mtev_defines.h \
  ../mtev_config.h ../noitedit/strlcpy.h ../eventer/eventer.h \
  ../../src/utils/mtev_log.h ../utils/mtev_hash.h \
  ../../src/utils/mtev_atomic.h ../eventer/eventer_POSIX_fd_opset.h \
  ../eventer/eventer_SSL_fd_opset.h ../eventer/eventer_jobq.h \
  ../../src/utils/mtev_sem.h ../libmtev_dtrace_probes.h
eventer_SSL_fd_opset.o: eventer_SSL_fd_opset.c ../mtev_defines.h \
  ../mtev_config.h ../noitedit/strlcpy.h ../eventer/eventer.h \
  ../../src/utils/mtev_log.h ../utils/mtev_hash.h \
  ../../src/utils/mtev_atomic.h ../eventer/eventer_POSIX_fd_opset.h \
  ../eventer/eventer_SSL_fd_opset.h ../eventer/eventer_jobq.h \
  ../../src/utils/mtev_sem.h ../eventer/OETS_asn1_helper.h \
  ../libmtev_dtrace_probes.h
eventer_impl.o: eventer_impl.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../eventer/eventer.h ../../src/utils/mtev_log.h \
  ../utils/mtev_hash.h ../../src/utils/mtev_atomic.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h ../../src/utils/mtev_sem.h \
  ../../src/utils/mtev_memory.h ../../src/utils/mtev_skiplist.h \
  ../../src/utils/mtev_watchdog.h ../libmtev_dtrace_probes.h
eventer_jobq.o: eventer_jobq.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../../src/utils/mtev_memory.h \
  ../../src/utils/mtev_log.h ../utils/mtev_hash.h \
  ../../src/utils/mtev_atomic.h ../eventer/eventer.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h ../../src/utils/mtev_sem.h \
  ../libmtev_dtrace_probes.h
eventer_kqueue_impl.o: eventer_kqueue_impl.c ../mtev_defines.h \
  ../mtev_config.h ../noitedit/strlcpy.h ../eventer/eventer.h \
  ../../src/utils/mtev_log.h ../utils/mtev_hash.h \
  ../../src/utils/mtev_atomic.h ../eventer/eventer_POSIX_fd_opset.h \
  ../eventer/eventer_SSL_fd_opset.h ../eventer/eventer_jobq.h \
  ../../src/utils/mtev_sem.h ../../src/utils/mtev_skiplist.h \
  ../../src/utils/mtev_memory.h ../libmtev_dtrace_probes.h \
  ../eventer/eventer_impl_private.h
