describe("misc", function()
  it("getaddrinfo should resolve localhost", function()
    local ip, fam, addr = mtev.getaddrinfo("localhost")
    assert.are.equal(ip, "127.0.0.1")
    assert.are.equal(fam, "inet")
  end)

  it("inet_pton should parse ip addresses", function()
       local ok, fam, addr = mtev.inet_pton("1.2.3.4")
       assert.are.equal(ok, true)
       assert.are.equal(fam, "inet")
       assert.are.equal(type(addr), "userdata")

       local ok, fam, addr = mtev.inet_pton("2001:db8:85a3:0:0:8a2e:370:7334")
       assert.are.equal(ok, true)
       assert.are.equal(fam, "inet6")
       assert.are.equal(type(addr), "userdata")
  end)
end)
