
mtev_b32.o mtev_b32.lo: mtev_b32.c ../mtev_config.h mtev_b64.h ../mtev_defines.h \
  ../noitedit/strlcpy.h

mtev_b64.o mtev_b64.lo: mtev_b64.c ../mtev_config.h mtev_b64.h ../mtev_defines.h \
  ../noitedit/strlcpy.h

mtev_btrie.o mtev_btrie.lo: mtev_btrie.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../utils/mtev_btrie.h

mtev_getip.o mtev_getip.lo: mtev_getip.c ../mtev_config.h ../utils/mtev_getip.h \
  ../mtev_defines.h ../noitedit/strlcpy.h ../eventer/eventer.h \
  mtev_log.h ../utils/mtev_hash.h mtev_atomic.h \
  ../eventer/eventer_POSIX_fd_opset.h ../eventer/eventer_SSL_fd_opset.h \
  ../eventer/eventer_jobq.h mtev_sem.h

mtev_hash.o mtev_hash.lo: mtev_hash.c ../mtev_config.h mtev_hash.h

mtev_lockfile.o mtev_lockfile.lo: mtev_lockfile.c ../mtev_config.h \
  ../utils/mtev_lockfile.h ../mtev_defines.h ../noitedit/strlcpy.h

mtev_log.o mtev_log.lo: mtev_log.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../utils/mtev_log.h ../utils/mtev_hash.h \
  ../utils/mtev_atomic.h ../libmtev_dtrace_probes.h

mtev_memory.o mtev_memory.lo: mtev_memory.c ../utils/mtev_log.h ../mtev_defines.h \
  ../mtev_config.h ../noitedit/strlcpy.h ../utils/mtev_hash.h

mtev_mkdir.o mtev_mkdir.lo: mtev_mkdir.c ../mtev_config.h ../utils/mtev_mkdir.h \
  ../mtev_defines.h ../noitedit/strlcpy.h ../utils/mtev_log.h \
  ../utils/mtev_hash.h

mtev_security.o mtev_security.lo: mtev_security.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../utils/mtev_log.h ../utils/mtev_hash.h \
  ../utils/mtev_security.h

mtev_sem.o mtev_sem.lo: mtev_sem.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../utils/mtev_sem.h

mtev_skiplist.o mtev_skiplist.lo: mtev_skiplist.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h mtev_skiplist.h

mtev_str.o mtev_str.lo: mtev_str.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h

mtev_watchdog.o mtev_watchdog.lo: mtev_watchdog.c ../mtev_defines.h ../mtev_config.h \
  ../noitedit/strlcpy.h ../eventer/eventer.h mtev_log.h \
  ../utils/mtev_hash.h mtev_atomic.h ../eventer/eventer_POSIX_fd_opset.h \
  ../eventer/eventer_SSL_fd_opset.h ../eventer/eventer_jobq.h mtev_sem.h \
  ../utils/mtev_watchdog.h
